export const ArcanaType = {
  CardType: {
    Joker: 0,
    Unit: 1,
    Evoluve: 2,
    Intercept: 3,
    Trigger: 4
  },
  Species: {
    Null: 0,
    珍獣: 1,
    戦士: 2,
    魔道士: 3,
    精霊: 4,
    悪魔: 5,
    獣: 5,
    機械: 6,
    巨人: 7,
    海洋: 8,
    不死: 9,
    英雄: 10,
    神: 11,
    侍: 12,
    天使: 13,
    忍者: 14,
    昆虫: 15,
    盗賊: 16,
    道化師: 17,
    神獣: 18,
    舞姫: 19,
    四聖獣: 20,
    武身: 21,
    ドラゴン: 22,
    ウィルス: 23,
  },
  Color: {
    None: 0,
    Red: 1,
    Yellow: 2,
    Blue: 3,
    Green: 4,
    Purple: 5,
  },
  Event: {
    Joker: 'Joker',
    Boot: 'Boot',
    OnTurnStart: 'OnTurnStart',
    OnTurnEnd: 'OnTurnEnd',
    OnDrive: 'OnDrive',
    OnClockUp: 'OnClockUp',
    OnOverClock: 'OnOverClock',
    OnAttack: 'OnAttack',
    OnBlock: 'OnBlock',
    OnBattleStart: 'OnBattle',
    OnBattleEnd: 'OnBattleEnd',
    OnBreak: 'OnBreak',
    OnDelete: 'OnDelete',
    OnBounce: 'OnBounce',
    OnDamage: 'OnDamage',
    OnSuccessPlayerAttack: 'OnSuccessPlayerAttack',
    OnHandDestraction: 'OnHandDestraction',
    OnCPIncrease: 'OnCPIncrease',
    OnJoker: 'OnJoker',
  }
}

